# -*- coding: utf-8 -*-
"""Proyek_Analisis_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DzJj4R75otGXZuzzk3yI5RS7gWje7Ocw

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** Wahyu Nurhabib
- **Email:** cdcc009d6y0631@student.devacademy.id
- **ID Dicoding:** cdcc009d6y0631

## Menentukan Pertanyaan Bisnis

**SMART Question** adalah sebuah framework untuk merumuskan pertanyaan secara terstruktur agar memeperoleh informasi yang mendalam.

* **Spesific (Spesifik)**
  * Pertanyaan harus jelas, fokus pada sebuah topik tertentu, dan tidak bermakna ganda. Hindari pertanyaan yang terlalu luas.
    * Salah: Bagaimana cara meningkatkan penjualan?
    * Benar: Faktor apa saja yang memengaruhi penurunan penjualan produk kategori elektronik di wilayah Jakarta selama kuartal terakhir?
* **Measurable (Terukur)**
  * Pertanyaan harus bisa dijawab dengan angka atau matrix yang konkret, harus tahu apa yang akan dihitung.
    * Salah: Apakah pelanggan senang dengan layanan kita?
    * Benar: Berapa skor rata-rata Customer Satisfaction untuk layanan purna jual bulan ini dibandingkan bulan lalu?
* **Action-Oriented (Berorientasi Aksi)**
  * Hasil dari pertanyaan harus bisa memberikan arahan untuk melakukan tindakan nyata. Jika pertanyaan terjawab, stakeholder harus tahu apa langkah selanjutnya.
    * Salah: Mengapa orang suka berbelanja?
    * Benar: Fitur apa pada aplikasi yang paling sering digunakan sebelum pengguna memutuskan untuk melakukan checkout?
* **Relevant (Relevan)**
  * Hasil dari pertanyaan harus sejalan dengan tujuan utama bisnis atau masalah yang sedang dihadapi.
    * Salah: Menanyakan tentang stok gudang saat masalah utamanya adalah efektivitas kampanye media sosial.
    * Benar: Apakah kampanye iklan di Instagram memberikan Return on Ad Spend (ROAS) yang lebih tinggi dibandingkan iklan di TikTok?
* **Time-bound (Terikat Waktu)**
  * Pertanyaan harus ada batasan waktu yang jelas agar analisis memiliki konteks yang tepat.
    * Salah: Berapa banyak pengguna baru kita?
    * Benar: Berapa tingkat pertumbuhan pengguna baru secara bulanan (Month-over-Month) sepanjang tahun 2025?

**Contoh pertanyaan bisnis yang memenuhi seluruh elemen SMART**

***"Faktor apa saja yang memengaruhi penurunan conversion rate pada pengguna aplikasi Android di wilayah Jabodetabek sebesar 5% selama periode Flash Sale Maret 2026?"***

Keterangan:

- **Specific**: Fokus pada "penurunan conversion rate" untuk "aplikasi Android" di "Jabodetabek". Bukan sekadar penjualan turun.
- **Measurable**: Ada angka konkret yang ingin dianalisis, yaitu penurunan sebesar "5%".
- **Action-Oriented**: Dengan mengetahui faktor penyebabnya misalnya bug pada versi Android tertentu atau kendala logistik di Jabodetabek, tim bisa langsung melakukan perbaikan teknis atau operasional.
- **Relevant**: Penurunan konversi saat Flash Sale adalah masalah kritis bagi bisnis retail/e-commerce.
- **Time-bound**: Dibatasi pada periode spesifik "Flash Sale Maret 2026".

- **Pertanyaan 1:**
***"“Bagaimana pengaruh peningkatan rata-rata konsentrasi PM2.5 terhadap kenaikan jumlah hari dengan kategori kualitas udara tidak sehat di wilayah Dongsi selama musim dingin periode November 2015 hingga Februari 2016?”"***

Keterangan:

- **Specific**: Fokus pada konsentrasi PM2.5 dan kategori kualitas udara di wilayah Dongsi.
- **Measurable**: Menggunakan rata-rata konsentrasi PM2.5 dan jumlah hari kategori tidak sehat..
- **Action-Oriented**: Hasil analisis dapat digunakan pemerintah atau perusahaan untuk menentukan kebijakan pengurangan polusi udara.
- **Relevant**: Relevan terhadap isu lingkungan dan kesehatan masyarakat.
- **Time-bound**: Dibatasi pada musim dingin November 2015 sampai Februari 2016.

- **Pertanyaan 2:**
***"Apakah kecepatan angin rata-rata di wilayah Changping berpengaruh terhadap penurunan konsentrasi PM10 sebesar minimal 10% selama periode Januari sampai Juni 2016?"***

Keterangan:

- **Specific**: Fokus pada hubungan kecepatan angin dan konsentrasi PM10 di Changping.
- **Measurable**: Mengukur kecepatan angin rata-rata dan penurunan PM10 minimal 10%.
- **Action-Oriented**: Dapat menjadi dasar strategi mitigasi polusi dan penempatan area penghijauan.
- **Relevant**: Relevan untuk analisis kualitas udara dan pengendalian pencemaran.
- **Time-bound**: Dibatasi pada Januari hingga Juni 2016.

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np

# Visualisasi
import matplotlib.pyplot as plt
import seaborn as sns

# Pengaturan visual
sns.set(style='whitegrid')
plt.rcParams['figure.figsize'] = (12,6)

# Mengabaikan warning
import warnings
warnings.filterwarnings('ignore')

"""## Data Wrangling

### Gathering Data

#### Load df ...
"""

# Import dataset
aotizhongxin_df = pd.read_csv('/content/PRSA_Data_Aotizhongxin_20130301-20170228.csv')
changping_df = pd.read_csv('/content/PRSA_Data_Changping_20130301-20170228.csv')
dingling_df = pd.read_csv('/content/PRSA_Data_Dingling_20130301-20170228.csv')
dongsi_df = pd.read_csv('/content/PRSA_Data_Dongsi_20130301-20170228.csv')
guanyuan_df = pd.read_csv('/content/PRSA_Data_Guanyuan_20130301-20170228.csv')
gucheng_df = pd.read_csv('/content/PRSA_Data_Gucheng_20130301-20170228.csv')
huairou_df = pd.read_csv('/content/PRSA_Data_Huairou_20130301-20170228.csv')
nongzhanguan_df = pd.read_csv('/content/PRSA_Data_Nongzhanguan_20130301-20170228.csv')
shunyi_df = pd.read_csv('/content/PRSA_Data_Shunyi_20130301-20170228.csv')
tiantan_df = pd.read_csv('/content/PRSA_Data_Tiantan_20130301-20170228.csv')
wanliu_df = pd.read_csv('/content/PRSA_Data_Wanliu_20130301-20170228.csv')
wanshouxigong_df = pd.read_csv('/content/PRSA_Data_Wanshouxigong_20130301-20170228.csv')

# Menggabungkan seluruh dataset
all_df = pd.concat([
    aotizhongxin_df,
    changping_df,
    dingling_df,
    dongsi_df,
    guanyuan_df,
    gucheng_df,
    huairou_df,
    nongzhanguan_df,
    shunyi_df,
    tiantan_df,
    wanliu_df,
    wanshouxigong_df
], ignore_index=True)

# Menampilkan 5 data teratas
all_df.head()

"""**Insight:** (Opsional)
Dataset berisi data kualitas udara dari beberapa stasiun pemantauan di Beijing periode 2013–2017.
Variabel utama meliputi PM2.5, PM10, suhu, tekanan udara, curah hujan, dan kecepatan angin.
Dataset memiliki jumlah data yang besar sehingga cocok untuk analisis tren polusi udara.
Namun ditemukan beberapa missing values pada beberapa kolom seperti PM2.5, PM10, dan O3.

### Assessing Data

#### Identifying ... problem
"""

all_df.isna().sum()
all_df.duplicated().sum()
all_df.dtypes

"""**Steps to Take:**
Beberapa masalah ditemukan pada dataset:

Terdapat missing values pada beberapa variabel kualitas udara.
Format tanggal masih terpisah menjadi year, month, day, dan hour.
Terdapat kemungkinan inkonsistensi tipe data.
Dataset perlu dibersihkan agar analisis lebih akurat.

**Insight:** (Opsional)
Langkah yang akan dilakukan untuk menyelesaikan masalah:

Mengatasi missing values menggunakan metode imputasi median.
Menggabungkan kolom waktu menjadi format datetime.
Memastikan tidak ada data duplikat.
Menyesuaikan tipe data agar konsisten.

### Cleaning Data

#### Fixing ... problem
"""

all_df.drop_duplicates(inplace=True)

columns_fill = ['PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3']

for col in columns_fill:
    all_df[col].fillna(all_df[col].median(), inplace=True)

all_df['datetime'] = pd.to_datetime(
    all_df[['year', 'month', 'day', 'hour']]
)

all_df.isna().sum()

"""**Insight:** (Opsional)
Data berhasil dibersihkan dari duplikasi dan missing values utama.
Kolom datetime berhasil dibuat sehingga analisis berbasis waktu dapat dilakukan dengan lebih mudah.
Dataset kini lebih siap digunakan untuk eksplorasi dan visualisasi.

## Exploratory Data Analysis (EDA)

### Explore ...
"""

all_df.groupby('station')['PM2.5'].mean().sort_values(ascending=False)

all_df.groupby('station')['PM10'].mean().sort_values(ascending=False)

correlation = all_df[['PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3', 'TEMP', 'WSPM']].corr()

plt.figure(figsize=(10,8))
sns.heatmap(correlation, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

"""**Insight:** (Opsional)
Beberapa stasiun memiliki rata-rata PM2.5 dan PM10 yang lebih tinggi dibanding lainnya.
Terdapat korelasi positif antara PM2.5 dan PM10.
Kecepatan angin (WSPM) cenderung berkorelasi negatif dengan PM10, yang menunjukkan bahwa angin dapat membantu mengurangi konsentrasi polutan di udara.

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

# Filter data Dongsi
dongsi_winter = all_df[
    (all_df['station'] == 'Dongsi') &
    (all_df['datetime'] >= '2015-11-01') &
    (all_df['datetime'] <= '2016-02-29')
]

# Visualisasi PM2.5
plt.figure(figsize=(14,6))
plt.plot(dongsi_winter['datetime'], dongsi_winter['PM2.5'])

plt.title('PM2.5 Dongsi (Winter 2015-2016)')
plt.xlabel('Date')
plt.ylabel('PM2.5')
plt.show()

"""### Pertanyaan 2:"""

# Filter data Changping
changping_df = all_df[
    (all_df['station'] == 'Changping') &
    (all_df['datetime'] >= '2016-01-01') &
    (all_df['datetime'] <= '2016-06-30')
]

# Scatterplot hubungan WSPM dan PM10
plt.figure(figsize=(10,6))

sns.scatterplot(
    x='WSPM',
    y='PM10',
    data=changping_df
)

plt.title('Hubungan Kecepatan Angin dan PM10')
plt.xlabel('Wind Speed (WSPM)')
plt.ylabel('PM10')
plt.show()

"""**Insight:** (Opsional)
- Konsentrasi PM2.5 mengalami peningkatan signifikan pada beberapa periode musim dingin.
Hal ini menunjukkan kualitas udara yang memburuk selama musim dingin di wilayah Dongsi.
- Kecepatan angin yang lebih tinggi cenderung diikuti penurunan konsentrasi PM10.
Hal ini menunjukkan angin berperan dalam menyebarkan partikel polusi sehingga konsentrasi udara menjadi lebih rendah.

## Analisis Lanjutan (Opsional)
"""



"""**Insight:** (Opsional)
- xxx
- xxx

## Conclusion & Recommendation

- **Conclusion pertanyaan 1:** Peningkatan konsentrasi PM2.5 di Dongsi selama musim dingin 2015–2016 menyebabkan meningkatnya jumlah hari dengan kualitas udara tidak sehat.
Musim dingin menjadi periode dengan risiko polusi udara lebih tinggi.

- **Conclusion pertanyaan 2:** Kecepatan angin memiliki hubungan negatif terhadap konsentrasi PM10 di Changping.
Semakin tinggi kecepatan angin, konsentrasi PM10 cenderung menurun.

**Rekomendasi Action Item:**

1. Pemerintah perlu meningkatkan pengawasan emisi kendaraan dan industri selama musim dingin.
2. Sistem peringatan dini kualitas udara perlu ditingkatkan pada periode polusi tinggi.
3. Penambahan ruang terbuka hijau dapat membantu mengurangi konsentrasi polusi udara.
4. Monitoring kualitas udara berbasis real-time perlu diperluas di seluruh wilayah.
5. Kampanye penggunaan transportasi umum perlu ditingkatkan untuk mengurangi emisi kendaraan pribadi.
"""